@Library('dxp-pipeline-library')_
node {
   def mvnHome
   stage('Demo') {
        echo 'Hello world'
        sayHello 'Dave'
   }
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/suswan-mondal/course-api.git'
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.           
      mvnHome = tool 'mvn3.6'
   }
   stage('Build') {
      // Run the maven build
      if (isUnix()) {
         sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
      } else {
         bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
      }
   }
   stage('Results') {
      junit '**/target/surefire-reports/TEST-*.xml'
      archive 'target/*.jar'
   }
}