@Library('dxp-pipeline-library')_
node {
   def mvnHome
   def z = new libraryFunctions()
   //stage('Demo') {
        //echo 'Hello world'
        //sayHello 'Dave'
		//evenOrOdd(3)
			
  //}
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      //git 'https://github.com/suswan-mondal/course-api.git'
	  
	  def repo = "https://github.com/suswan-mondal/course-api.git"	 
	  z.checkOutFrom(repo)
     
   }
   stage('Build') {
      
       // Get the Maven tool.           
      mvnHome = tool 'mvn3.6'
	  
	  // Run the maven build
	  z.mavenBuild(mvnHome)
   }
   stage('Results') {
     // junit '**/target/surefire-reports/TEST-*.xml'
      archive 'target/*.jar'
   }
}