@Library('dxp-pipeline-library')_
node {
	def mvnHome
	def methods = new libraryFunctions() 

	stage('Preparation') { // for display purposes
		// Get some code from a GitHub repository
		def repo = "https://github.com/suswan-mondal/course-api.git"
		methods.checkOutFrom(repo)

	}
	stage('Build') {

		// Get the Maven tool.
		mvnHome = tool 'mvn3.6'

		// Run the maven build
		methods.mavenBuild(mvnHome)
	}
	stage('Deploy'){
		echo "~~~Deploy~~~"
		bat "set"		
		
		bat "pscp C:/Users/Administrator/.jenkins/workspace/dxpcommerce/target/course-api-0.0.1-SNAPSHOT.jar  aws_linux_ec2-18-130-243-17:/home/ec2-user"		
	}
	stage('Results') {
		// junit '**/target/surefire-reports/TEST-*.xml'
		archive 'target/*.jar'
	}
}